image: ruby:2.5.1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/ruby

before_script:
  - ruby -v
  - gem install bundler --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor

rspec:
  script:
    - bundle exec rspec

rubocop:
  script:
    - bundle exec rubocop